/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.object.storage.sharepoint.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.object.storage.sharepoint.model.TokenEntry;
import com.liferay.object.storage.sharepoint.model.TokenEntryModel;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the TokenEntry service. Represents a row in the &quot;OSSharepoint_TokenEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>TokenEntryModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TokenEntryImpl}.
 * </p>
 *
 * @author Jürgen Kappler
 * @see TokenEntryImpl
 * @generated
 */
public class TokenEntryModelImpl
	extends BaseModelImpl<TokenEntry> implements TokenEntryModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a token entry model instance should use the <code>TokenEntry</code> interface instead.
	 */
	public static final String TABLE_NAME = "OSSharepoint_TokenEntry";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"tokenEntryId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"accessToken", Types.CLOB},
		{"expirationDate", Types.TIMESTAMP}, {"refreshToken", Types.CLOB}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("tokenEntryId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("accessToken", Types.CLOB);
		TABLE_COLUMNS_MAP.put("expirationDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("refreshToken", Types.CLOB);
	}

	public static final String TABLE_SQL_CREATE =
		"create table OSSharepoint_TokenEntry (mvccVersion LONG default 0 not null,tokenEntryId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,accessToken TEXT null,expirationDate DATE null,refreshToken TEXT null)";

	public static final String TABLE_SQL_DROP =
		"drop table OSSharepoint_TokenEntry";

	public static final String ENTITY_ALIAS = "tokenEntry";

	public static final String ORDER_BY_JPQL =
		" ORDER BY tokenEntry.tokenEntryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY OSSharepoint_TokenEntry.tokenEntryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long USERID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TOKENENTRYID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public TokenEntryModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _tokenEntryId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setTokenEntryId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _tokenEntryId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TokenEntry.class;
	}

	@Override
	public String getModelClassName() {
		return TokenEntry.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<TokenEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<TokenEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TokenEntry, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((TokenEntry)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<TokenEntry, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<TokenEntry, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(TokenEntry)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<TokenEntry, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<TokenEntry, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<TokenEntry, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<TokenEntry, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<TokenEntry, Object>>();

			attributeGetterFunctions.put(
				"mvccVersion", TokenEntry::getMvccVersion);
			attributeGetterFunctions.put(
				"tokenEntryId", TokenEntry::getTokenEntryId);
			attributeGetterFunctions.put("groupId", TokenEntry::getGroupId);
			attributeGetterFunctions.put("companyId", TokenEntry::getCompanyId);
			attributeGetterFunctions.put("userId", TokenEntry::getUserId);
			attributeGetterFunctions.put("userName", TokenEntry::getUserName);
			attributeGetterFunctions.put(
				"createDate", TokenEntry::getCreateDate);
			attributeGetterFunctions.put(
				"accessToken", TokenEntry::getAccessToken);
			attributeGetterFunctions.put(
				"expirationDate", TokenEntry::getExpirationDate);
			attributeGetterFunctions.put(
				"refreshToken", TokenEntry::getRefreshToken);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<TokenEntry, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<TokenEntry, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<TokenEntry, ?>>();

			attributeSetterBiConsumers.put(
				"mvccVersion",
				(BiConsumer<TokenEntry, Long>)TokenEntry::setMvccVersion);
			attributeSetterBiConsumers.put(
				"tokenEntryId",
				(BiConsumer<TokenEntry, Long>)TokenEntry::setTokenEntryId);
			attributeSetterBiConsumers.put(
				"groupId",
				(BiConsumer<TokenEntry, Long>)TokenEntry::setGroupId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<TokenEntry, Long>)TokenEntry::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId", (BiConsumer<TokenEntry, Long>)TokenEntry::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<TokenEntry, String>)TokenEntry::setUserName);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<TokenEntry, Date>)TokenEntry::setCreateDate);
			attributeSetterBiConsumers.put(
				"accessToken",
				(BiConsumer<TokenEntry, String>)TokenEntry::setAccessToken);
			attributeSetterBiConsumers.put(
				"expirationDate",
				(BiConsumer<TokenEntry, Date>)TokenEntry::setExpirationDate);
			attributeSetterBiConsumers.put(
				"refreshToken",
				(BiConsumer<TokenEntry, String>)TokenEntry::setRefreshToken);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@Override
	public long getTokenEntryId() {
		return _tokenEntryId;
	}

	@Override
	public void setTokenEntryId(long tokenEntryId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_tokenEntryId = tokenEntryId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalUserId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("userId"));
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public String getAccessToken() {
		if (_accessToken == null) {
			return "";
		}
		else {
			return _accessToken;
		}
	}

	@Override
	public void setAccessToken(String accessToken) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_accessToken = accessToken;
	}

	@Override
	public Date getExpirationDate() {
		return _expirationDate;
	}

	@Override
	public void setExpirationDate(Date expirationDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_expirationDate = expirationDate;
	}

	@Override
	public String getRefreshToken() {
		if (_refreshToken == null) {
			return "";
		}
		else {
			return _refreshToken;
		}
	}

	@Override
	public void setRefreshToken(String refreshToken) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_refreshToken = refreshToken;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), TokenEntry.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TokenEntry toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, TokenEntry>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TokenEntryImpl tokenEntryImpl = new TokenEntryImpl();

		tokenEntryImpl.setMvccVersion(getMvccVersion());
		tokenEntryImpl.setTokenEntryId(getTokenEntryId());
		tokenEntryImpl.setGroupId(getGroupId());
		tokenEntryImpl.setCompanyId(getCompanyId());
		tokenEntryImpl.setUserId(getUserId());
		tokenEntryImpl.setUserName(getUserName());
		tokenEntryImpl.setCreateDate(getCreateDate());
		tokenEntryImpl.setAccessToken(getAccessToken());
		tokenEntryImpl.setExpirationDate(getExpirationDate());
		tokenEntryImpl.setRefreshToken(getRefreshToken());

		tokenEntryImpl.resetOriginalValues();

		return tokenEntryImpl;
	}

	@Override
	public TokenEntry cloneWithOriginalValues() {
		TokenEntryImpl tokenEntryImpl = new TokenEntryImpl();

		tokenEntryImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		tokenEntryImpl.setTokenEntryId(
			this.<Long>getColumnOriginalValue("tokenEntryId"));
		tokenEntryImpl.setGroupId(this.<Long>getColumnOriginalValue("groupId"));
		tokenEntryImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		tokenEntryImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		tokenEntryImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		tokenEntryImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		tokenEntryImpl.setAccessToken(
			this.<String>getColumnOriginalValue("accessToken"));
		tokenEntryImpl.setExpirationDate(
			this.<Date>getColumnOriginalValue("expirationDate"));
		tokenEntryImpl.setRefreshToken(
			this.<String>getColumnOriginalValue("refreshToken"));

		return tokenEntryImpl;
	}

	@Override
	public int compareTo(TokenEntry tokenEntry) {
		long primaryKey = tokenEntry.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof TokenEntry)) {
			return false;
		}

		TokenEntry tokenEntry = (TokenEntry)object;

		long primaryKey = tokenEntry.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<TokenEntry> toCacheModel() {
		TokenEntryCacheModel tokenEntryCacheModel = new TokenEntryCacheModel();

		tokenEntryCacheModel.mvccVersion = getMvccVersion();

		tokenEntryCacheModel.tokenEntryId = getTokenEntryId();

		tokenEntryCacheModel.groupId = getGroupId();

		tokenEntryCacheModel.companyId = getCompanyId();

		tokenEntryCacheModel.userId = getUserId();

		tokenEntryCacheModel.userName = getUserName();

		String userName = tokenEntryCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			tokenEntryCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			tokenEntryCacheModel.createDate = createDate.getTime();
		}
		else {
			tokenEntryCacheModel.createDate = Long.MIN_VALUE;
		}

		tokenEntryCacheModel.accessToken = getAccessToken();

		String accessToken = tokenEntryCacheModel.accessToken;

		if ((accessToken != null) && (accessToken.length() == 0)) {
			tokenEntryCacheModel.accessToken = null;
		}

		Date expirationDate = getExpirationDate();

		if (expirationDate != null) {
			tokenEntryCacheModel.expirationDate = expirationDate.getTime();
		}
		else {
			tokenEntryCacheModel.expirationDate = Long.MIN_VALUE;
		}

		tokenEntryCacheModel.refreshToken = getRefreshToken();

		String refreshToken = tokenEntryCacheModel.refreshToken;

		if ((refreshToken != null) && (refreshToken.length() == 0)) {
			tokenEntryCacheModel.refreshToken = null;
		}

		return tokenEntryCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<TokenEntry, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<TokenEntry, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<TokenEntry, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((TokenEntry)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, TokenEntry>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					TokenEntry.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private long _tokenEntryId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private String _accessToken;
	private Date _expirationDate;
	private String _refreshToken;

	public <T> T getColumnValue(String columnName) {
		Function<TokenEntry, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((TokenEntry)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put("tokenEntryId", _tokenEntryId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("accessToken", _accessToken);
		_columnOriginalValues.put("expirationDate", _expirationDate);
		_columnOriginalValues.put("refreshToken", _refreshToken);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("tokenEntryId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("accessToken", 128L);

		columnBitmasks.put("expirationDate", 256L);

		columnBitmasks.put("refreshToken", 512L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private TokenEntry _escapedModel;

}
// LIFERAY-SERVICE-BUILDER-HASH:-840772259