/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.object.storage.sharepoint.model.impl;

import com.liferay.object.storage.sharepoint.model.TokenEntry;
import com.liferay.object.storage.sharepoint.service.TokenEntryLocalServiceUtil;

/**
 * The extended model base implementation for the TokenEntry service. Represents a row in the &quot;OSSharepoint_TokenEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TokenEntryImpl}.
 * </p>
 *
 * @author Jürgen Kappler
 * @see TokenEntryImpl
 * @see TokenEntry
 * @generated
 */
public abstract class TokenEntryBaseImpl
	extends TokenEntryModelImpl implements TokenEntry {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a token entry model instance should use the <code>TokenEntry</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			TokenEntryLocalServiceUtil.addTokenEntry(this);
		}
		else {
			TokenEntryLocalServiceUtil.updateTokenEntry(this);
		}
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:435663906