/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.object.storage.sharepoint.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the TokenEntry service. Represents a row in the &quot;OSSharepoint_TokenEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.object.storage.sharepoint.model.impl.TokenEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.object.storage.sharepoint.model.impl.TokenEntryImpl</code>.
 * </p>
 *
 * @author Jürgen Kappler
 * @see TokenEntry
 * @generated
 */
@ProviderType
public interface TokenEntryModel
	extends BaseModel<TokenEntry>, MVCCModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a token entry model instance should use the {@link TokenEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this token entry.
	 *
	 * @return the primary key of this token entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this token entry.
	 *
	 * @param primaryKey the primary key of this token entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this token entry.
	 *
	 * @return the mvcc version of this token entry
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this token entry.
	 *
	 * @param mvccVersion the mvcc version of this token entry
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the token entry ID of this token entry.
	 *
	 * @return the token entry ID of this token entry
	 */
	public long getTokenEntryId();

	/**
	 * Sets the token entry ID of this token entry.
	 *
	 * @param tokenEntryId the token entry ID of this token entry
	 */
	public void setTokenEntryId(long tokenEntryId);

	/**
	 * Returns the group ID of this token entry.
	 *
	 * @return the group ID of this token entry
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this token entry.
	 *
	 * @param groupId the group ID of this token entry
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this token entry.
	 *
	 * @return the company ID of this token entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this token entry.
	 *
	 * @param companyId the company ID of this token entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this token entry.
	 *
	 * @return the user ID of this token entry
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this token entry.
	 *
	 * @param userId the user ID of this token entry
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this token entry.
	 *
	 * @return the user uuid of this token entry
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this token entry.
	 *
	 * @param userUuid the user uuid of this token entry
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this token entry.
	 *
	 * @return the user name of this token entry
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this token entry.
	 *
	 * @param userName the user name of this token entry
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this token entry.
	 *
	 * @return the create date of this token entry
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this token entry.
	 *
	 * @param createDate the create date of this token entry
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the access token of this token entry.
	 *
	 * @return the access token of this token entry
	 */
	@AutoEscape
	public String getAccessToken();

	/**
	 * Sets the access token of this token entry.
	 *
	 * @param accessToken the access token of this token entry
	 */
	public void setAccessToken(String accessToken);

	/**
	 * Returns the expiration date of this token entry.
	 *
	 * @return the expiration date of this token entry
	 */
	public Date getExpirationDate();

	/**
	 * Sets the expiration date of this token entry.
	 *
	 * @param expirationDate the expiration date of this token entry
	 */
	public void setExpirationDate(Date expirationDate);

	/**
	 * Returns the refresh token of this token entry.
	 *
	 * @return the refresh token of this token entry
	 */
	@AutoEscape
	public String getRefreshToken();

	/**
	 * Sets the refresh token of this token entry.
	 *
	 * @param refreshToken the refresh token of this token entry
	 */
	public void setRefreshToken(String refreshToken);

	@Override
	public TokenEntry cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:1008176862